version: '3'
services:
  db:
    image: "postgres:11"
    environment:
      POSTGRES_USER: rcos
      POSTGRES_PASSWORD: password
    ports:
      - 0.0.0.0:5432:5432

  data-collection:
    build: .
    volumes:
      - .:/repo/hedgehogs
    depends_on:
      - db
